# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor:
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# A pager program to send command output to, e.g. "less". Set the value to "cat" to disable the pager.
pager:
# Aliases allow you to create nicknames for gh commands
aliases:
    co: pr checkout
    dev: cs create --status -r github/github
    edu: cs create --status -r github/education-web
    pf: cs ports forward 80:80 2206:2206 8081:8081
    pfe: cs ports forward 9461:9461
    ep: cs ports forward 9461:9461
version: "1"
